import { Provider } from "react-redux";
import "../styles/global.scss";
import { Inter } from "next/font/google";
import store from "@/redux/store";
import StoreProvider from "@/components/StoreProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  // viewport: {
  //   width: "device-width",
  //   initialScale: 1,
  // },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} overflow-hidden`}>
        <StoreProvider>{children}</StoreProvider>
        <div id="portal"></div>
      </body>
    </html>
  );
}
